# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/footballmanager',
                'doc_host': 'https://FineNine.github.io',
                'git_url': 'https://github.com/FineNine/footballmanager',
                'lib_path': 'footballmanager'},
  'syms': {'footballmanager.core': {'footballmanager.core.foo': ('core.html#foo', 'footballmanager/core.py')}}}
